name: Run updates.sh
on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run updates.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: Run updates.sh
        run: ./src/updates.sh
